onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - sharp

allowBuilds:
  '@clerk/shared': true
  esbuild: true
  sharp: true

overrides:
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
